#!/usr/bin/env php
<?php

  $port = 80;
  $ret = shell_exec("nmap -p $port $argv[1] 2>&1");

  $latency = NULL;

  if(!empty($ret))
  {
    $results = explode("\n", $ret);
    
    $latency = explode("(", $results[sizeof($results) - 6]);
    if(sizeof($latency) >=2)
    {
      $latency = explode("s", $latency[1]);
      if(sizeof($latency) >=1)
      {
        $latency = floatval($latency[0]);
      }
    }
  }

  echo $latency;

?>
