#!/usr/bin/env php
<?php

  $port = 80;
  $ret = shell_exec("nmap -p $port $argv[1] 2>&1");

  $state_value = NULL;

  if(!empty($ret))
  {
    $results = explode("\n", $ret);
    
    if(sizeof($results) == 9)
    {
      $state = explode(" ", $results[sizeof($results) - 4]);
      if(sizeof($state) >= 2)
      {
        $state = $state[1];
        if(strcasecmp($state, "open") == 0)
          $state_value = 1;
        elseif(strcasecmp($state, "closed") == 0)
          $state_value = 0;
        else
          $state_value = 2;
      }
    }
  }

  echo "$state_value";

?>
