#!/usr/bin/env php
<?php

  $port = 80;
  $ret = shell_exec("nmap -p $port $argv[1] 2>&1");

  $state_value = NULL;

  if(!empty($ret))
  {
    $results = explode("\n", $ret);
    
    $state = explode(" ", $results[sizeof($results) - 4]);
    if(sizeof($state) >= 2)
    {
      $state = $state[1];
      if($state == "open")
        $state_value = 1;
      elseif($state == "closed")
        $state_value = 0;
      else
        $state_value = 2;
    }
  }

  echo "$state_value";

?>
