#!/usr/bin/env php
<?php

  $port = 80;
  $ret = shell_exec("nmap -n -p $port $argv[1] 2>&1");

  $latency = NULL;

  if(!empty($ret))
  {
    $results = explode("\n", $ret);

    if(sizeof($results) == 8)
    {
      $latency = explode(" ", $results[sizeof($results)-2]);
			$latency = floatval($latency[10]);
    }
  }

  echo $latency;

?>
