#!/usr/bin/env php
<?php

  $count = 5;
  $ret = shell_exec("ping -c $count $argv[1] 2>&1");
  
  $loss = NULL;

  if(!empty($ret))
  {
    $results = explode("\n", $ret);

    if(sizeof($results) == 6 || sizeof($results) == $count+6)
    {
      $results = explode(" ", $results[sizeof($results) - 3]);

      $results = explode("%", $results[5]);
      if(sizeof($results) >= 1)
        $loss = $results[0];
    }
  }

  echo $loss;

?>
