#!/usr/bin/env php
<?php

  $count = 5;
  $ret = shell_exec("ping -c $count $argv[1] 2>&1");
  $loss = -1;

  if(!empty($ret))
  {
    $results = explode("\n", $ret);

    if (sizeof($results) == $count+6)
    {
      $loss = explode(" ", $results[(sizeof($results)-3)]);
      $loss = explode("%", $loss[5]);
      $loss = intval($loss[0]);
    }
  }

  echo $loss;

?>
