#!/usr/bin/env php
<?php

  $oid = "1.3.6.1.2.1.25.2.3.1.6.$argv[2]";
  $ret = shell_exec("snmpget -O Uen -v 1 -c public $argv[1] $oid 2>&1");

  if(!empty($ret) && (substr($ret, 0, strlen("Timeout")) != "Timeout"))
  {
    $used = explode(" ", $ret);
    $used = $used[sizeof($used) - 1];
  }

  $oid = "1.3.6.1.2.1.25.2.3.1.4.$argv[2]";
  $ret = shell_exec("snmpget -O Uen -v 1 -c public $argv[1] $oid 2>&1");

  if(!empty($ret) && (substr($ret, 0, strlen("Timeout")) != "Timeout"))
  {
    $units = explode(" ", $ret);
    $units = $units[sizeof($units) - 1];
  }

  if(!is_null($used) && !is_null($units))
    $value = intval($used) * intval($units);

  echo "-1 $value";

?>
