#!/usr/bin/env php
<?php

  $oid = "1.3.6.1.2.1.25.2.3.1.5.$argv[3]";

  if(empty($argv[1]))
    $community = "public";
  else
    $community = $argv[1];

  $ret = shell_exec("snmpget -O Uen -v 1 -c $community $argv[2] $oid 2>&1");

  $value = NULL;
  $size = NULL;
  $used = NULL;
  $units = NULL;

  if(!empty($ret) && (strcasecmp(substr($ret, 0, strlen("Timeout")), "Timeout") != 0) && (preg_match("/Unknown Object Identifier/", $ret) == 0))
  {
    $size = explode(" ", $ret);
    $size = $size[sizeof($size) - 1];
  }

  $oid = "1.3.6.1.2.1.25.2.3.1.6.$argv[3]";
  $ret = shell_exec("snmpget -O Uen -v 1 -c $community $argv[2] $oid 2>&1");

  if(!empty($ret) && (strcasecmp(substr($ret, 0, strlen("Timeout")), "Timeout") != 0))
  {
    if(preg_match("/Unknown Object Identifier/", $ret) == 0)
    {
      $used = explode(" ", $ret);
      $used = $size[sizeof($used) - 1];
    }
  }

  $oid = "1.3.6.1.2.1.25.2.3.1.4.$argv[3]";
  $ret = shell_exec("snmpget -O Uen -v 1 -c $community $argv[2] $oid 2>&1");

  if(!empty($ret) && (strcasecmp(substr($ret, 0, strlen("Timeout")), "Timeout") != 0))
  {
    if(preg_match("/Unknown Object Identifier/", $ret) == 0)
    {
      $units = explode(" ", $ret);
      $units = $units[sizeof($units) - 1];
    }
  }



  if(!is_null($size) && !is_null($used) && (strcmp($units, "()\n") != 0))
    $value = (intval($size) - intval($used)) * intval($units);

  echo "-1 $value";

?>
