#!/usr/bin/env php
<?php

  $oid = "1.3.6.1.4.1.2021.4.6.0";

  if(empty($argv[1]))
    $community = "public";
  else
    $community = $argv[1];

  $ret = shell_exec("snmpget -O Uen -v 1 -c $community $argv[2] $oid 2>&1");

  $value = NULL;

  if(!empty($ret) && (strcasecmp(substr($ret, 0, strlen("Timeout")), "Timeout") != 0))
  {
    $value = explode(" ", $ret);
    $value = $value[sizeof($value) - 1] * 1024;
  }

  echo "$oid $value";

?>
